version : '3.8'
services:
    db:
        image: mysql:latest
        container_name: ${container_name}
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
           MYSQL_DATABASE: ${MYSQL_DATABASE} 
           MYSQL_USER: ${MYSQL_USER} 
           MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
         - 3306:3306 
        volumes:
        - ./db-data/db:/var/lib/mysql
